[tool.pytest.ini_options]
addopts = "-v --alluredir=/Users/priscilahirotsu/pessoal/estudo/projetos/test-playwright-python/reports/allure-results --clean-alluredir"
filterwarnings = ["ignore::UserWarning"]