#inicializar os testes
[tool.pytest.ini.options]

#config de reports de execução do teste
addopts = "-v --alluredir=/Users/priscilahirotsu/pessoal/estudo/projetos/test-playwright-python/reports/allure-results --clean-alluredir"
filterwarnings = ['ignore::UserWarning']


